### PR TITLE
Feat: add basic IFC exporter

### PR DESCRIPTION
**Pull request by ENG-Mazri**

### CODE REVIEW

**Comment by madil4** [comment]
I tried to export a model but got this error as shown below

```RuntimeError: Aborted(both async and sync fetching of the wasm failed). Build with -sASSERTIONS for more info.```
 
Screenshot 2024-06-16 at 9 38 22 PM

**Comment by ENG-Mazri** [comment]
weird it worked for me, basically this is because it can't find wasm files to run the IFC parser, I'll do that differently

**Comment by madil4** [comment]
> weird it worked for me, basically this is because it can't find wasm files to run the IFC parser, I'll do that differently

Why do we need a parser since we are not reading IFC but writing files? better not to include it if possible

**Comment by ENG-Mazri** [comment]
we need a parser to write an IFC model, and by the way during the writing we also read some lines to link them to other objects

**Comment by ENG-Mazri** [comment]
https://github.com/madil4/awatif/assets/84850871/dee626ff-06ed-405b-9a8d-e9ed9a479230

I'm not able to reproduce that error, have you installed the 0.0.54 of web-ifc package ?

**Comment by madil4** [comment]
We will pick this up again in later stages, now we have a new plan and pivot for the development which requires us to export IFC objects as well. I will keep you posted

**Pull request closed without merging**
